# Generated by Django 5.2.5 on 2025-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Email_address', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField(max_length=10)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
