# Generated by Django 5.2.5 on 2025-08-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='ContactPage',
        ),
        migrations.AlterModelTable(
            name='contactpage',
            table=None,
        ),
    ]
