# Generated by Django 5.2.5 on 2025-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('mini_title', models.CharField(max_length=120)),
                ('main_title', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='')),
                ('about_title', models.CharField(max_length=255)),
                ('about_description', models.TextField()),
            ],
        ),
    ]
